name: CD

on:
    workflow_dispatch: 

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Check kubernetes
              run: kubectl get nodes

            - name: Deploy application
              run: |
                kubectl apply -f k8s/app/deployment.yaml
                kubectl apply -f k8s/app/service.yaml

            - name: Wait for rollout
              run: |
                kubectl rollout status deployment/contact-app -n contact-app

            - name: Verify deployment
              run: |
                kubectl get pods -n contact-app
                kubectl get deployment contact-app -n contact-app