name: CD

on:
    workflow_dispatch: 

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Check kubernetes
              run: kubectl get nodes

            - name: Check current pods
              run: kubectl get pods -n contact-app