name: CD

on:
    workflow_dispatch:
        inputs:
            image_tag:
                description: "Docker Image tag to deploy"
                required: true
                type: string

jobs:
    deploy:
        runs-on: self-hosted

        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Check kubernetes
              run: kubectl get nodes

            - name: Deploy application
              shell: bash
              run: |
                kubectl -n contact-app set image deployment/contact-app \
                contact-app=${{ secrets.DOCKERHUB_USERNAME }}/contact-form-app:${{ inputs.image_tag }}

            - name: Wait for rollout
              run: |
                kubectl rollout status deployment/contact-app \
                  -n contact-app \
                  --timeout=120s

            - name: Verify deployment
              run: |
                kubectl get pods -n contact-app
                kubectl get deployment contact-app -n contact-app