name: Self Hosted Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Check kubectl
        run: kubectl version --client

      - name: Check Kubernetes
        run: kubectl get nodes